export default {
  address: "42 West St<br>Suite 339<br>Brooklyn, NY<br>11222",
  email: "hello@newinfo.studio",
  emailString: "hello@<wbr>newinfo.studio",
  instagram: "https://www.instagram.com/newinfo.studio/",
  textColumn1:
    "New Information is an award-winning design studio partnering with culturally-forward institutions and brands.<br><br>Services<br>Brand Strategy<br>Brand Identity Design<br>Web Design<br>Art Direction<br>Creative Direction<br>Motion Design<br>Exhibition Design<br>Signage Design<br>Publication Design<br><br> Current & Past Clients<br>Agency—Agency<br>AIA New York<br>American Literary Translators Association<br>Arper<br>Artsy<br>Asian American Arts Alliance<br>Atrbute<br>Away<br>Columbia Books on Architecture and the City<br>Cory Arcangel<br>Emerson Collective<br>Ford Foundation<br>Gap<br>Google<br>Homecoming<br>Krink<br>Levis<br>Mastic Beach Conservancy<br>Mexican Summer<br>Moda Operandi<br>MoMA<br>Monacelli Press<br>Nike<br>Patagonia<br>PennDesign<br>Peterson Rich Office<br>Processing Foundation<br>Queens Museum<br>Robert Rauschenberg Foundation<br>Rubin Museum of Art<br>Spitzer School of Architecture<br>Skowhegan School of Painting & Sculpture<br>Storefront for Art & Architecture<br>Teva<br>Two Palms<br>Urban Outfitters<br>Van Alen Institute<br>Vera List Center for Art and Politics<br>vowels<br>Walker Art Center<br>Whitney Museum of American Art<br><br><br>",
  textColumn2:
    'Based in Brooklyn, New Information focuses on brand strategy, identity, digital, and publication design for cultural institutions and businesses across the arts, design, technology, and fashion. We see design as a conduit to connect people, ideas, and objects in the world. We lead with curiosity and rigor to create meaningful design solutions that drive culture forward.<br><br>Led by Dave Yun (co-founder of Wax Studios and formerly 2x4, Pentagram), our core team is dedicated to building a selection of high-quality design projects each year. Unlike large agencies, our detail-oriented approach ensures that clients receive direct attention and support, lending to a dynamic and nimble workflow.<br><br>Collaborators<br><a href="https://dexinchen.net/" target="_blank">⭢ Dexin Leah Chen</a><br><a href="https://inyeongcho.com/" target="_blank">⭢ Inyeong Cho</a><br><a href="https://cold-rice.info/" target="_blank">⭢ Cold Rice</a><br><a href="https://www.juliafiore.com/" target="_blank">⭢ Julia Fiore</a><br>⭢ S. Gong<br><a href="https://scott-haven.com/" target="_blank">⭢ Scott Haven</a><br><a href="https://weiweihuanghuang.github.io/" target="_blank">⭢ Wei Huang</a><br><a href="https://hunni.dev/" target="_blank">⭢ Hunni Dev</a><br>⭢ Cong Huynh<br><a href="https://eddiedohyun.kim/" target="_blank">⭢ Eddie Dohyun Kim</a><br><a href="https://jaiwon.work/" target="_blank">⭢ Jaiwon Lee</a><br><a href="https://www.studiominheelee.com/" target="_blank">⭢ Min Hee Lee</a><br><a href="https://andrewliu.site/" target="_blank">⭢ Andrew Haoyuan Liu</a><br><a href="https://sachamaric.com/" target="_blank">⭢ Sacha Maric</a><br><a href="https://kellenrenstrom.com/" target="_blank">⭢ Kellen Renstrom</a><br><a href="https://stefanietam.com/" target="_blank">⭢ Stefanie Tam</a><br>'
};
